---
id: groonga-document-read-1
base_name: introduction
tags:
- rabbit
- groonga
presentation_date: 2014-05-15
version: 2014.5.15.2
licenses:
- CC BY-SA 4.0
slideshare_id: groonga-document-read-1
speaker_deck_id: groongadokiyumentodu-shu-hui-1falsejin-mefang
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
